WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entities;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }

}

WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurentPages { get; set; }
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

WebUI/Models/ProductsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entities;

namespace WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo {get; set;}
        public string CurentCategory { get; set; }
    }
}

WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using SportsStore.Domain.Concrete;
namespace WebUI.Controllers
{
    public class AdminController : Controller
    {
        private IProductRepository repository;

        public AdminController(IProductRepository repo)
        {
            repository = repo;
        }
        //
        // GET: /Admin/

        public ViewResult Index()
        {
            return View(repository.Products);
        }
        public ViewResult Edit(int productId)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            return View(product);
        }
        [HttpPost]
        public ActionResult Edit(Product product,HttpPostedFileBase image)
        {
            if(ModelState.IsValid)
            {
                if (image!=null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }
                repository.SaveProducts(product);
                TempData["message"] = string.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
               
            }
            else
            {
                return View(product);
            }
        }
        public ViewResult Create()
        {
            return View("Edit", new Product());
        }
        [HttpPost]
        public ActionResult Delete(int productId)
        {
            Product deleteProduct = repository.DeleteProduct(productId);
            if(deleteProduct!=null)
            {
                TempData["message"] = string.Format("{0} was deleted", deleteProduct.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        //
        // GET: /Cart/
        private IProductRepository repository;
        public CartController (IProductRepository repo)
        {
            repository = repo;
           
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl });
        }
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if(product!=null)
            {
                cart.AddItem(product, 1);
                
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFormCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.RemoveLine(product);

            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if(cart.Lines.Count()==0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                
                cart.Clear();
                return View("Completed", shippingDetails);
            }
            else
            {
                return View(shippingDetails);
            }
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }



    }
}

WebUI/Controllers/NavController.cs
using System;
using Domain.Abstract;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        //
        // GET: /Nav/
        private IProductRepository repository;
        public NavController(IProductRepository repo)
        {
            this.repository = repo;
        }

        public PartialViewResult Menu(string category=null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> catigories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(catigories);
        }

    }
}

WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using WebUI.Models;
namespace WebUI.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/
        private IProductRepository repository;
        public int PageSize = 4;
        public ProductController(IProductRepository productRepository)
        {
            this.repository = productRepository;
        }

        public ViewResult List(string category, int page=1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products
                    .Where(p=>category==null||p.Category==category)
                    .OrderBy(p => p.Name)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurentPages = page,
                    ItemsPerPage = PageSize,
                    TotalItems =category==null? repository.Products.Count():
                    repository.Products.Where(e=>e.Category==category).Count()
                },
                CurentCategory=category
            };
            return View(model);
        }
        public FileContentResult GetImage(int productId)
        {
            Product prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

WebUI/Views/Admin/Edit.cshtml
@model Domain.Entities.Product

@{
    ViewBag.Title = "Admin:Edit"+@Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
 

<h1>Edit @Model.Name</h1>
@using(Html.BeginForm("Edit","Admin",
    FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    
    @Html.EditorForModel()
    <div class="editor-label">Image</div>
    <div class="editor-field">
        @if(Model.ImageData==null)
        {
            @:None
        }
        else
        {
            <img width="150" height="150" src="@Url.Action("GetImage","Product", new {Model.ProductID})"/>
        }
     <div> Upload new image:
           <input type="file" name="Image"/></div>
    </div>
     
    <input type="submit" value="Save"/>
    @Html.ActionLink("Cancel and return to lList","Index")
}

WebUI/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th class="NumericCol"> Price</th>
        <th>Action</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@item.ProductID </td>
        <td> @Html.ActionLink(item.Name,"Edit", new {item.ProductID})</td>
        <td class="NumericCol"> @item.Price.ToString("c") </td>
        <td>
            @using(Html.BeginForm("Delete","Admin"))
            {
                @Html.Hidden("ProductID",item.ProductID)
                <input type="submit" value="Delete"/>
            }
        </td>
    </tr>
}

</table>
<p>@Html.ActionLink("Add a new product", "Create")</p>

WebUI/Views/Cart/Checkout.cshtml
@model Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Product/Shared/_Layout.cshtml";
}

<h2>Check out now</h2>
Please enter your details, and we'll ship your goods right away!
@using(Html.BeginForm())
{
    @Html.ValidationSummary()
    <h3>Ship to</h3>
    <div>Nmae: @Html.EditorFor(x=>x.Name)</div>
    <h3>Adress</h3>
    <div>Line1: @Html.EditorFor(x=>x.Line1)</div>
    <div>Line2: @Html.EditorFor(x=>x.Line2)</div>
    <div>Line3: @Html.EditorFor(x=>x.Line3)</div>
    <div>City: @Html.EditorFor(x=>x.City)</div>
    <div>State: @Html.EditorFor(x=>x.State)</div>
    <div>Zip: @Html.EditorFor(x=>x.Zip)</div>
    <div>Country: @Html.EditorFor(x=>x.Country)</div>
    <h3>Option</h3>
    <label>
        @Html.EditorFor(x=>x.GiftWarp)
        Gift wrap these items
    </label>
    
    <p align="center">
        <input class="actionButtons" type="submit" value="Complete order"/>
    </p>
}

WebUI/Views/Cart/Completed.cshtml
@model Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Completed";
    Layout = "~/Views/Product/Shared/_Layout.cshtml";
}


<h2>Thanks! @Model.Name </h2>
Thanks for placing your order. We'll ship your goods as soon as possible. We send products to @Model.Line1.

WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel

@{
  ViewBag.Title = "Sports Store: Your Cart";
  Layout = "~/Views/Product/Shared/_Layout.cshtml";
}

<h2>Your cart</h2>
<table width="90%" align="center">
    <thead>
        <tr>
            <th align="center">Quantity</th>
            <th align="left">Item</th>
            <th align="right">Price</th>
            <th align="right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td align="center">@line.Quantity</td>
                <td align="left">@line.Product.Name</td>
                <td align="right">@line.Product.Price.ToString("c")</td>
                <td align="right">@((line.Quantity * line.Product.Price).ToString("c"))</td>
                <td>
                    @using (Html.BeginForm("RemoveFormCart", "Cart")) {
                    @Html.Hidden("ProductId",line.Product.ProductID)
                    @Html.HiddenFor(x=>x.ReturnUrl)
                        <input class="actionButtons" type="submit" value="Remove"/>
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" align="right">Total:</td>
            <td align="right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<p align="center" class="actionButtons">
    <a href="@Model.ReturnUrl">Continue shopping</a>
    @Html.ActionLink("Checkout now", "Checkout")
    
</p>

WebUI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart
<div id="cart">
    <span class="caption">
        <b>Your cart:</b>
        @Model.Lines.Sum(x=>x.Quantity) item(s)
        @Model.ComputeTotalValue().ToString("c")
    </span>
    @Html.ActionLink("Checkot", "Index", "Cart", new { returnUrl=Request.Url.PathAndQuery},null)
</div>

WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List","Product")

@foreach(var link in Model)
{
    @Html.RouteLink(link, new 
    {
        controller="Product",
        action="List",
        category=link,
        page=1
    },
      new{
          @class=link==ViewBag.SelectedCategory?"selected":null
      })
      
}

WebUI/Views/Product/List.cshtml
@model WebUI.Models.ProductsListViewModel
@using WebUI.HtmlHelpers;

@{
    ViewBag.Title = "Products";
    Layout = "Shared/_Layout.cshtml";
}

<h2>List prducts</h2>

@foreach (var p in Model.Products)
{
    Html.RenderPartial("Shared/ProductSummary", p);
}

<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category=Model.CurentCategory}))
</div>

WebUI/Views/Product/Shared/ProductSummary.cshtml
@model Domain.Entities.Product
<div class="item">
    @if (Model.ImageData != null)
    {
        <div style="float: left; margin-right: 20px">
            <img width="75" height="75" src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
        </div>
    }
    <h3>@Model.Name</h3>
   <h3> @Model.Description</h3>
    @using (Html.BeginForm("AddToCart", "Cart")) { 
    
        @Html.HiddenFor(x=>x.ProductID)
        @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
        <input  class="cart" type="submit" value="+ Add to cart"/>
    }
    <h4>@Model.Price.ToString("c")</h4>
</div>

WebUI/Views/Product/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/Cart.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div id="header">
       @{Html.RenderAction("Summary", "Cart");}
        <div class="title">SPORTS STORE</div>
    </div>
    <div id="categories">
        @{Html.RenderAction("Menu", "Nav");}
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/Admin_Edit.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.7.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @if(TempData["message"]!=null)
        {
            <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>